In [1]:
from google.colab import files
  
  
uploaded = files.upload()

Saving url_data.csv to url_data.csv

**Loading the data**

In [2]:
#importing basic packages
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
#Loading the data
data0 = pd.read_csv("url_data.csv")
data0.head()

   id  having_IP_Address  ...  Statistical_report  Result
0   1                 -1  ...                  -1      -1
1   2                  1  ...                   1      -1
2   3                  1  ...                  -1      -1
3   4                  1  ...                   1      -1
4   5                  1  ...                   1       1

[5 rows x 32 columns]

**Data Precprocessing**

In [5]:
data0.describe()

                 id  having_IP_Address  ...  Statistical_report        Result
count  11055.000000       11055.000000  ...        11055.000000  11055.000000
mean    5528.000000           0.313795  ...            0.719584      0.113885
std     3191.447947           0.949534  ...            0.694437      0.993539
min        1.000000          -1.000000  ...           -1.000000     -1.000000
25%     2764.500000          -1.000000  ...            1.000000     -1.000000
50%     5528.000000           1.000000  ...            1.000000      1.000000
75%     8291.500000           1.000000  ...            1.000000      1.000000
max    11055.000000           1.000000  ...            1.000000      1.000000

[8 rows x 32 columns]

In [6]:
#Dropping the id column
data = data0.drop(['id'], axis = 1).copy()

In [7]:
#checking the data for null or missing values
data.isnull().sum()

having_IP_Address              0
URL_Length                     0
Shortining_Service             0
having_At_Symbol               0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWidnow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistical_report             0
Result                         0
dtype: int64

In [8]:
# shuffling the rows in the dataset so that when splitting the train and test set are equally distributed
data = data.sample(frac=1).reset_index(drop=True)
data.head()

   having_IP_Address  URL_Length  ...  Statistical_report  Result
0                  1           1  ...                   1      -1
1                  1          -1  ...                   1       1
2                  1          -1  ...                   1       1
3                  1          -1  ...                   1       1
4                  1          -1  ...                   1      -1

[5 rows x 31 columns]

**Split the data**

In [9]:
# Sepratating & assigning features and target columns to X & y
y = data['Result']
X = data.drop('Result',axis=1)
X.shape, y.shape

((11055, 30), (11055,))

In [10]:
# Splitting the dataset into train and test sets: 80-20 split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.2, random_state = 12)
X_train.shape, X_test.shape

((8844, 30), (2211, 30))

**Support vector machine**

In [11]:
#Support vector machine model
from sklearn.svm import SVC

# instantiate the model
svm = SVC(kernel='linear', C=1.0, random_state=12)
#fit the model
svm.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=12, shrinking=True, tol=0.001,
    verbose=False)

In [12]:
#predicting the target value from the model for the samples
y_test_svm = svm.predict(X_test)
y_train_svm = svm.predict(X_train)

**Performance Evaluation**

In [13]:
#importing packages
from sklearn.metrics import accuracy_score

# Creating holders to store the model performance results
ML_Model = []
acc_train = []
acc_test = []

#function to call for storing the results
def storeResults(model, a,b):
  ML_Model.append(model)
  acc_train.append(round(a, 3))
  acc_test.append(round(b, 3))

In [14]:
#computing the accuracy of the model performance
acc_train_svm = accuracy_score(y_train,y_train_svm)
acc_test_svm = accuracy_score(y_test,y_test_svm)

print("SVM: Accuracy on training Data: {:.3f}".format(acc_train_svm))
print("SVM : Accuracy on test Data: {:.3f}".format(acc_test_svm))

SVM: Accuracy on training Data: 0.930
SVM : Accuracy on test Data: 0.925

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_test_svm)
print(cm)

[[ 852   90]
 [  76 1193]]